name: test

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read
  issues: write
  checks: write

jobs:
  automated-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "bun" # Use bun for caching dependencies
          cache-dependency-path: "bun.lockb"

      - name: Install bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"

      - name: Install dependencies
        run: bun install

      - name: Install Playwright browsers
        run: npx playwright install chromium --with-deps

      - name: Run unit tests
        run: bun run test
        continue-on-error: true
        timeout-minutes: 3

      - name: Run integration tests
        run: bun run playwright
        continue-on-error: true
        timeout-minutes: 5

      - name: Report unit test results
        uses: mikepenz/action-junit-report@v2
        if: success() || failure()
        with:
          report_paths: "**/unit-test-results.xml"
          check_name: "Unit Tests Report"

      - name: Report integration test results
        uses: mikepenz/action-junit-report@v2
        if: success() || failure()
        with:
          report_paths: "**/integration-test-results.xml"
          check_name: "Integration Tests Report"
